#! /bin/sh

killall -q eww &
sxhkd &
picom &
nitrogen --restore &

eww daemon
eww open mybar

bspc monitor primary -d 1 2 3 4 5

bspc config top_padding         55
bspc config border_width         2
bspc config window_gap          15

#------------ Color scheme configuration ----------------------#

bspc config normal_border_color		"#11111B"
bspc config active_border_color		"#11111B"
bspc config focused_border_color	"#11111B"
bspc config presel_feedback_color "#11111B"
# bspc config presel_feedback_color	"#89B4FA"

#------------ BSPWM Rules -------------------------------------#

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
