#! /bin/sh

killall -q eww &
sxhkd &
picom &
nitrogen --restore &

eww daemon
eww open mybar

bspc monitor primary -d 1 2 3 4 5 6

bspc config top_padding         55
bspc config border_width         1
bspc config window_gap          5

#------------ Color scheme configuration ----------------------#

bspc config normal_border_color		"#11111B"
bspc config active_border_color		"#11111B"
bspc config focused_border_color	"#fab387"
bspc config presel_feedback_color "#fab387"
# bspc config presel_feedback_color	"#89B4FA"

#------------ BSPWM Rules -------------------------------------#

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc rule -a Nitrogen state=floating 
bspc rule -a firefox desktop='^2' focus=on follow=on
bspc rule -a obsidian desktop='^3' focus=on follow=on
bspc rule -a discord desktop='^5'  focus=off follow=off
bspc rule -a Screenkey manage=off
